package com.jmstextbot.dreamteam.entities;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

import java.time.LocalDateTime;

@Document(collection = "CustomerDriver")
public class CustomerDriver {

    @Id
    private String id;
    @Transient // this value is generated by mongo, this is only a representation
    private final String _class = "com.jmstextbot.dreamteam.entities.CustomerDriver";
    @Field("email")
    @Indexed(unique = true)
    private String email;
    @Field("phoneNumber")
    @Indexed(unique = true)
    private String phoneNumber;
    @Field("firstName")
    private String firstName;
    @Field("lastName")
    private String lastName;
    @Field("companyName")
    private String companyName;
    @Field("dateCreated")
    @DateTimeFormat(iso = ISO.DATE_TIME)
    private LocalDateTime dateCreated;

    public CustomerDriver(String email, String phoneNumber, LocalDateTime dateCreated) {
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.dateCreated = dateCreated;
    }

    public CustomerDriver(String email, String phoneNumber, String firstName, String lastName, String companyName, LocalDateTime dateCreated) {
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.companyName = companyName;
        this.dateCreated = dateCreated;
    }

    public LocalDateTime getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Override
    public String toString() {
        return "Person [id=" +
                id + ", name=" +
                firstName + " " +
                lastName + ", email=" +
                email + ", company=" +
                companyName + ", phone=" +
                phoneNumber + "]";
    }
}
